from typing import Optional, Dict, Any
from pydantic import BaseModel, Field


class DocumentChunk(BaseModel):
    """
    Upstream Interface Contract (M1 -> M2).
    Output generated by M1 (Chunking) and consumed by M2 (Embedding Engineer).
    """
    document_id: str = Field(..., description="Source legal document ID")
    chunk_id: str = Field(..., description="Unique chunk ID within the document")
    text: str = Field(..., description="Chunk text content")
    page: Optional[int] = Field(default=None, description="Page number")
    section: Optional[str] = Field(default=None, description="Document section or article title")
    language: str = Field(default="ar", description="Language of chunk text")
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Additional metadata")
