from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class QueryFilters(BaseModel):
    """
    Metadata filtering parameters passed from M2.
    """
    document_type: Optional[str] = Field(
        default=None,
        description="Type of legal document (e.g., contract, law, decree, court_verdict)"
    )
    jurisdiction: Optional[str] = Field(
        default=None,
        description="Legal jurisdiction (e.g., Egypt, KSA, UAE, international)"
    )
    language: Optional[str] = Field(
        default=None,
        description="Language filter (e.g., ar, en)"
    )
    extra_filters: Optional[Dict[str, Any]] = Field(
        default_factory=dict,
        description="Custom additional filter criteria"
    )

class IdentifierSet(BaseModel):
    article_numbers: List[str] = Field(default_factory=list)
    case_numbers: List[str] = Field(default_factory=list)
    dates: List[str] = Field(default_factory=list)
    monetary_values: List[str] = Field(default_factory=list)
    party_names: List[str] = Field(default_factory=list)




class ProcessedQuery(BaseModel):
    """
    Upstream Interface Contract (M2 -> M3).
    Output generated by M2 (Embedding Engineer) and consumed by M3 (Retrieval Engineer).
    """
    query_id: str = Field(..., description="Unique query identifier")
    text_original: str = Field(..., description="Original user raw query text")
    normalized_text: str = Field(..., description="Preprocessed/normalized query text")
    language: str = Field(default="ar", description="Query language (ar, en, mixed)")
    embedding: Optional[List[float]] = Field(default_factory=list, description="BGE-M3 dense embedding vector (dim=1024)")
    sparse_embedding: Optional[Dict[str, float]] = Field(
        default=None,
        description="Optional sparse embedding indices/weights for hybrid BM25 search"
    )
    filters: QueryFilters = Field(
        default_factory=QueryFilters,
        description="Metadata filters to scope search space in vector store"
    )
    query_variants: Optional[List[str]] = Field(default_factory=list)
    identifiers: Optional[IdentifierSet] = Field(default=None)

class EmbeddedDocumentChunk(BaseModel):
    """
    Output generated by M2 (Embedding Engineer) for a single document chunk.
    """
    document_id: str = Field(..., description="Source legal document ID")
    chunk_id: str = Field(..., description="Unique chunk ID within the document")
    embedding: List[float] = Field(..., description="Dense embedding vector")
    model: str = Field(..., description="Embedding model name")
    dimension: int = Field(..., description="Embedding vector dimension")


class EmbeddedQuery(BaseModel):
    """
    Output generated by M2 for a processed query.
    """
    processed_query: ProcessedQuery = Field(..., description="The processed query")
    embedding: List[float] = Field(..., description="Dense embedding vector")
    model: str = Field(..., description="Embedding model name")
    dimension: int = Field(..., description="Embedding vector dimension")
